# MySQL
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3309/eusurveydb_rev2?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
# Credentials
jakarta.persistence.jdbc.user=eusurveyuser
jakarta.persistence.jdbc.password=eusurveyuser
#hibernate.default_schema=

# DDL
jakarta.persistence.schema-generation.database.action=update

# SQL statement logging
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# timezone
hibernate.jdbc.time_zone=Europe/Berlin

# disable use of JDBC database metadata
hibernate.boot.allow_jdbc_metadata_access=false

# explicitly specify database and version
jakarta.persistence.database-product-name=MySQL
jakarta.persistence.database-major-version=8
jakarta.persistence.database-minor-version=0

# connection pools
hibernate.connection.pool_size=
hibernate.connection.autocommit=
hibernate.connection.isolation=

# batch_size
hibernate.jdbc.batch_size=50
hibernate.default_batch_fetch_size=5
hibernate.use_subselect_fetch=true

# statistics
hibernate.generate_statistics=true

# legacy configs (imported from spring/hibernate-context.xml)
hibernate.connection.driver_class=net.bull.javamelody.JdbcDriver

hibernate.connection.provider_class=c3p0
hibernate.c3p0.min_size=10
hibernate.c3p0.max_size=20
hibernate.c3p0.max_statements=1
hibernate.c3p0.idle_test_period=100
hibernate.c3p0.timeout=300
hibernate.dialect.storage_engine=innodb

# code-breaking configs
hibernate.query.native.prefer_jdbc_datetime_types=true